### ISSUE TITLE
Not compatible with NUnit >= 3.0?

### ISSUE THREAD

**Issue by jpierson** [AkkaNetContrib/Akka.TestKit.Nunit#10]
I was attempting to set up my first set of unit tests and installed **NUnit 3.4.1** along with *_NUnit3TestAdapter_. I was able to get all of my regular NUnit tests to run in the test runner in Visual Studio 2015 Update 3 but none of the tests that inherited from TestKit were picked up by the test adapter. I'm guessing that this has to do with compatibility with NUnit 3 since removing the NUnit 3 references and replacing them along with the corresponding test adapter with their NUnit 2 counterparts appears to work as expected.

**Comment by Silv3rcircl3** [comment]
Could you share your tests?

**Comment by Danthar** [comment]
This is a known issue.

**Comment by jeblackburn** [comment]
Are there thoughts on whether & when to fix this? I have a hacky workaround in place that would be nice to kill off.

**Comment by Silv3rcircl3** [comment]
@jeblackburn could you share your workaround? After our gitter discussion I also tried it with NUnit 3.4.0 and it worked too.

**Comment by jeblackburn** [comment]
My workaround is nothing fancy. I'm corralling all of my Actor-dependent tests into a single project and importing NUnit 3.0 into that one. It moves the tests away from the business logic they're supposed to be testing, which as we scale will become a serious problem.

Are you saying you couldn't repeat the problem? I can zip up the test project that breaks for me if it will expedite things.

**Comment by jeblackburn** [comment]
@Silv3rcircl3 I confirmed that the problem exists for me using NUnit 3.2.0 as well.

**Comment by Silv3rcircl3** [comment]
Yes, it worked for me in any combination 3.0, 3.4.0 ... 
I would take a look if you could provide these tests, I will also try to update the Teskit to 3.4.0 and see if that works

**Comment by aimed** [comment]
Same problem here using NUnit 3.6.1 and Akka.TestKit.NUnit3 1.1.2.

**Comment by Aaronontheweb** [comment]
@aimed so the problem is that these specs aren't picked up by a VS extension for NUnit? Just want to make sure I understand

**Comment by aimed** [comment]
@Aaronontheweb exactly. The tests neither appeared in the VS extension nor within JetBrains Rider (EAP build 22, haven't checked since then).

**Comment by aimed** [comment]
@Aaronontheweb actually just double checked it again: at least in rider the Tests are displayed as tests and i can click on the run tests buttons etc, but once I try to run the the exception is show, something along the lines of "No TestFixture / Test found"

**Comment by ayoung** [comment]
@aimed @jpierson I believe this one can be closed. NUnit test adapter has trouble picking up on tests from libs that target netstandard. For test projects you have to target a version of netcore.

See [here](https://github.com/AkkaNetContrib/Akka.TestKit.Nunit/pull/25/commits/355a9d419a218e5d0cb3f57920275aaf9955b25a)
