### ISSUE TITLE
Deprecate Akka.TestKit.NUnit (NUnit 2.x) package

### ISSUE THREAD

**Issue by alexvaluyskiy** [AkkaNetContrib/Akka.TestKit.NUnit#23]
NUnit 3 was released about 2 years ago, and now it supports .Net Core. It is a good time to stop support NUnit 2 package

**Comment by Danthar** [comment]
+1

**Comment by ayoung** [comment]
Hahaha. Ok I'll take it out.

**Comment by alexvaluyskiy** [comment]
I think we still can release Akka.TestKit.NUnit (NUnit 2.x) package for 1.3.0, but we should mention, that this version will be the last one
