### ISSUE TITLE
Not compatible with Akka version 1.4.25+

### ISSUE THREAD

**Issue by bd-tom-cain** [AkkaNetContrib/Akka.TestKit.NUnit#41]
When running unit tests against source code that references 1.4.25+ (1.4.28), I get the following exception:

System.MissingMethodException : Method not found: 'Akka.Actor.IActorRef Akka.Actor.IInternalActorRef.GetChild(System.Collections.Generic.IEnumerable`1<System.String>)'.

**Comment by ok-ul-ch** [comment]
+1

**Comment by Aaronontheweb** [comment]
@bd-tom-cain @mralexes working on that now

**Comment by Aaronontheweb** [comment]
Will be released in v1.4.39 of this package, which we'll ship once https://github.com/akkadotnet/Akka.TestKit.NUnit/pull/56 is approved.
