### ISSUE TITLE
Support specifying an ActorSystem when [FixtureLifeCycle(LifeCycle.InstancePerTestCase)] is specified

### ISSUE THREAD

**Issue by mchandschuh** [AkkaNetContrib/Akka.TestKit.NUnit#44]
nunit 3.13 added `[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]` which should obviate the need for _code bombing_ when an `ActorSystem` is provided to the `TestKit` constructor.

**Describe the bug**
* Unable to specify `ActorSystem` in `TestKit` constructor

**To Reproduce**
* Try instantiating `TestKit` with an `ActorSystem`

See: https://github.com/akkadotnet/akka.net/pull/1092

**Comment by eaba** [comment]
Tell me more if it is not the right thing @mchandschuh https://github.com/akkadotnet/Akka.TestKit.NUnit/pull/45
