### ISSUE TITLE
NUKE: `GithubRelease` stage should not attempt to run during normal merges / PR validation

### ISSUE THREAD

**Issue by Aaronontheweb** [AkkaNetContrib/Akka.TestKit.NUnit#50]
See https://github.com/akkadotnet/Akka.TestKit.NUnit/runs/7430318885?check_suite_focus=true - that stage shouldn't run. Use exactly what's in https://github.com/petabridge/Petabridge.Library/.

> if Petabridge.Library does this too, that's a bug and it needs to be fixed there as well.

**Comment by eaba** [comment]
https://github.com/akkadotnet/Akka.TestKit.NUnit/pull/52
